apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bootstrap-secrets.yaml
  - redis.yaml
  - clickhouse.yaml
  - axiom-bootstrap.yaml
  - axiom-node.yaml
  - axiom-analytics-ml.yaml
  - monitoring.yaml
  - backup-cronjob.yaml

configMapGenerator:
  - name: clickhouse-init-config
    files:
      - init.sql=../../clickhouse/init.sql
